### ISSUE TITLE
s3 exception when no credentials set

### ISSUE THREAD

**Issue by limx0** [PrefectHQ/prefect-aws#102]
It appears as though a cryptic error is thrown if no credentials are defined in an S3 block and no credntials are defined locally either: 

```python

Traceback (most recent call last):
  File "/home/user/.cache/pypoetry/py3.10/lib/python3.10/site-packages/aiohttp/connector.py", line 986, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)  # type: ignore[return-value]  # noqa
  File "/usr/lib/python3.10/asyncio/base_events.py", line 1049, in create_connection
    sock = await self._connect_sock(
  File "/usr/lib/python3.10/asyncio/base_events.py", line 960, in _connect_sock
    await self.sock_connect(sock, address)
  File "/usr/lib/python3.10/asyncio/selector_events.py", line 499, in sock_connect
    return await fut
asyncio.exceptions.CancelledError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/user/.cache/pypoetry/py3.10/lib/python3.10/site-packages/aiohttp/client.py", line 535, in _request
    conn = await self._connector.connect(
  File "/home/user/.cache/pypoetry/py3.10/lib/python3.10/site-packages/aiohttp/connector.py", line 542, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "/home/user/.cache/pypoetry/py3.10/lib/python3.10/site-packages/aiohttp/connector.py", line 907, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "/home/user/.cache/pypoetry/py3.10/lib/python3.10/site-packages/aiohttp/connector.py", line 1175, in _create_direct_connection
    transp, proto = await self._wrap_create_connection(
  File "/home/user/.cache/pypoetry/py3.10/lib/python3.10/site-packages/aiohttp/connector.py", line 985, in _wrap_create_connection
    async with ceil_timeout(timeout.sock_connect):
  File "/home/user/.cache/pypoetry/py3.10/lib/python3.10/site-packages/async_timeout/__init__.py", line 129, in __aexit__
    self._do_exit(exc_type)
  File "/home/user/.cache/pypoetry/py3.10/lib/python3.10/site-packages/async_timeout/__init__.py", line 212, in _do_exit
    raise asyncio.TimeoutError
asyncio.exceptions.TimeoutError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/user/.cache/pypoetry/py3.10/lib/python3.10/site-packages/aiobotocore/httpsession.py", line 178, in send
    response = await self._session.request(
  File "/home/user/.cache/pypoetry/py3.10/lib/python3.10/site-packages/aiohttp/client.py", line 539, in _request
    raise ServerTimeoutError(
aiohttp.client_exceptions.ServerTimeoutError: Connection timeout to host http://169.254.169.254/latest/api/token

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/user/.cache/pypoetry/py3.10/lib/python3.10/site-packages/prefect/cli/_utilities.py", line 41, in wrapper
    return fn(*args, **kwargs)
  File "/home/user/.cache/pypoetry/py3.10/lib/python3.10/site-packages/prefect/utilities/asyncutils.py", line 212, in wrapper
    return run_async_in_new_loop(async_fn, *args, **kwargs)
  File "/home/user/.cache/pypoetry/py3.10/lib/python3.10/site-packages/prefect/utilities/asyncutils.py", line 141, in run_async_in_new_loop
    return anyio.run(partial(__fn, *args, **kwargs))
  File "/home/user/.cache/pypoetry/py3.10/lib/python3.10/site-packages/anyio/_core/_eventloop.py", line 70, in run
    return asynclib.run(func, *args, **backend_options)
  File "/home/user/.cache/pypoetry/py3.10/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 292, in run
    return native_run(wrapper(), debug=debug)
  File "/usr/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.10/asyncio/base_events.py", line 646, in run_until_complete
    return future.result()
  File "/home/user/.cache/pypoetry/py3.10/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 287, in wrapper
    return await func(*args)
  File "/home/user/.cache/pypoetry/py3.10/lib/python3.10/site-packages/prefect/cli/deployment.py", line 577, in build
    deployment = await Deployment.build_from_flow(
  File "/home/user/.cache/pypoetry/py3.10/lib/python3.10/site-packages/prefect/deployments.py", line 598, in build_from_flow
    await deployment.upload_to_storage()
  File "/home/user/.cache/pypoetry/py3.10/lib/python3.10/site-packages/prefect/deployments.py", line 465, in upload_to_storage
    file_count = await self.storage.put_directory(
  File "/home/user/.cache/pypoetry/py3.10/lib/python3.10/site-packages/prefect/filesystems.py", line 459, in put_directory
    return await self.filesystem.put_directory(
  File "/home/user/.cache/pypoetry/py3.10/lib/python3.10/site-packages/prefect/filesystems.py", line 342, in put_directory
    self.filesystem.put_file(f, fpath, overwrite=True)
  File "/home/user/.cache/pypoetry/py3.10/lib/python3.10/site-packages/fsspec/asyn.py", line 111, in wrapper
    return sync(self.loop, func, *args, **kwargs)
  File "/home/user/.cache/pypoetry/py3.10/lib/python3.10/site-packages/fsspec/asyn.py", line 96, in sync
    raise return_result
  File "/home/user/.cache/pypoetry/py3.10/lib/python3.10/site-packages/fsspec/asyn.py", line 53, in _runner
    result[0] = await coro
  File "/home/user/.cache/pypoetry/py3.10/lib/python3.10/site-packages/s3fs/core.py", line 1015, in _put_file
    await self._call_s3(
  File "/home/user/.cache/pypoetry/py3.10/lib/python3.10/site-packages/s3fs/core.py", line 325, in _call_s3
    await self.set_session()
  File "/home/user/.cache/pypoetry/py3.10/lib/python3.10/site-packages/s3fs/core.py", line 473, in set_session
    self._s3 = await s3creator.__aenter__()
  File "/home/user/.cache/pypoetry/py3.10/lib/python3.10/site-packages/aiobotocore/session.py", line 22, in __aenter__
    self._client = await self._coro
  File "/home/user/.cache/pypoetry/py3.10/lib/python3.10/site-packages/aiobotocore/session.py", line 102, in _create_client
    credentials = await self.get_credentials()
  File "/home/user/.cache/pypoetry/py3.10/lib/python3.10/site-packages/aiobotocore/session.py", line 133, in get_credentials
    self._credentials = await (self._components.get_component(
  File "/home/user/.cache/pypoetry/py3.10/lib/python3.10/site-packages/aiobotocore/credentials.py", line 814, in load_credentials
    creds = await provider.load()
  File "/home/user/.cache/pypoetry/py3.10/lib/python3.10/site-packages/aiobotocore/credentials.py", line 486, in load
    metadata = await fetcher.retrieve_iam_role_credentials()
  File "/home/user/.cache/pypoetry/py3.10/lib/python3.10/site-packages/aiobotocore/utils.py", line 175, in retrieve_iam_role_credentials
    token = await self._fetch_metadata_token()
  File "/home/user/.cache/pypoetry/py3.10/lib/python3.10/site-packages/aiobotocore/utils.py", line 88, in _fetch_metadata_token
    response = await session.send(request.prepare())
  File "/home/user/.cache/pypoetry/py3.10/lib/python3.10/site-packages/aiobotocore/httpsession.py", line 210, in send
    raise ConnectTimeoutError(endpoint_url=request.url, error=e)
botocore.exceptions.ConnectTimeoutError: Connect timeout on endpoint URL: "http://169.254.169.254/latest/api/token"
An exception occurred.
```

**Comment by ahuang11** [comment]
Thanks for reporting this!

I think this is related to the core Prefect's filesystem
https://github.com/PrefectHQ/prefect/blob/main/src/prefect/filesystems.py#L386

**Comment by ahuang11** [comment]
Please re-open if you still encounter this.
