### ISSUE TITLE
installing prefect_aws breaks aws s3 storage block usage 

### ISSUE THREAD

**Issue by rdenham** [PrefectHQ/prefect-aws#217]
If I have prefect working using an aws s3 storage block, and then install prefect_aws, I can no longer use the aws s3 block.

Presumably this is due to some aws package incompatibilities. Here is an example of it occurring:

Starting from a clean virtual environment, on ubuntu 20.22
```sh
python3 -m venv testv
# make sure you modify .prefectignore to exclude this, other
# wise you'll upload whole venv!
source ./testv/bin/activate
pip install -U pip
pip install prefect s3fs

prefect deployment build ./log_flow.py:log_flow    \
    -n s3test                              \
    -sb s3/scratchs3/ptut/        \
    -q test                                       \
    --param name="test run"
```

This works fine.

Now, if I install prefect_aws:

```sh
pip install prefect_aws

prefect deployment build ./log_flow.py:log_flow    \
    -n s3test                  \
    -sb s3/scratchs3/ptut/                          \
    -q test                                        \
    --param name="test run"
```

I get the following:

```
testv/lib/python3.9/site-packages/botocore/utils.py:1720: FutureWarning: The S3RegionRedirector class has been deprecated for a new internal replacement. A future version of botocore may remove this class.
  warnings.warn(
Traceback (most recent call last):
  File "/path/to/project/prefect_tutorial/testv/lib/python3.9/site-packages/s3fs/core.py", line 112, in _error_wrapper
    return await func(*args, **kwargs)
  File "/path/to/project/prefect_tutorial/testv/lib/python3.9/site-packages/aiobotocore/client.py", line 358, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.errorfactory.NoSuchBucket: An error occurred (NoSuchBucket) when calling the PutObject operation: The specified bucket does not exist

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/path/to/project/prefect_tutorial/testv/lib/python3.9/site-packages/prefect/cli/_utilities.py", line 41, in wrapper
    return fn(*args, **kwargs)
  File "/path/to/project/prefect_tutorial/testv/lib/python3.9/site-packages/prefect/utilities/asyncutils.py", line 230, in coroutine_wrapper
    return run_async_in_new_loop(async_fn, *args, **kwargs)
  File "/path/to/project/prefect_tutorial/testv/lib/python3.9/site-packages/prefect/utilities/asyncutils.py", line 181, in run_async_in_new_loop
    return anyio.run(partial(__fn, *args, **kwargs))
  File "/path/to/project/prefect_tutorial/testv/lib/python3.9/site-packages/anyio/_core/_eventloop.py", line 70, in run
    return asynclib.run(func, *args, **backend_options)
  File "/path/to/project/prefect_tutorial/testv/lib/python3.9/site-packages/anyio/_backends/_asyncio.py", line 292, in run
    return native_run(wrapper(), debug=debug)
  File "/usr/lib/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.9/asyncio/base_events.py", line 647, in run_until_complete
    return future.result()
  File "/path/to/project/prefect_tutorial/testv/lib/python3.9/site-packages/anyio/_backends/_asyncio.py", line 287, in wrapper
    return await func(*args)
  File "/path/to/project/prefect_tutorial/testv/lib/python3.9/site-packages/prefect/cli/deployment.py", line 1097, in build
    deployment = await Deployment.build_from_flow(
  File "/path/to/project/prefect_tutorial/testv/lib/python3.9/site-packages/prefect/deployments.py", line 764, in build_from_flow
    await deployment.upload_to_storage(ignore_file=ignore_file)
  File "/path/to/project/prefect_tutorial/testv/lib/python3.9/site-packages/prefect/deployments.py", line 609, in upload_to_storage
    file_count = await self.storage.put_directory(
  File "/path/to/project/prefect_tutorial/testv/lib/python3.9/site-packages/prefect/filesystems.py", line 494, in put_directory
    return await self.filesystem.put_directory(
  File "/path/to/project/prefect_tutorial/testv/lib/python3.9/site-packages/prefect/filesystems.py", line 370, in put_directory
    self.filesystem.put_file(f, fpath, overwrite=True)
  File "/path/to/project/prefect_tutorial/testv/lib/python3.9/site-packages/fsspec/asyn.py", line 115, in wrapper
    return sync(self.loop, func, *args, **kwargs)
  File "/path/to/project/prefect_tutorial/testv/lib/python3.9/site-packages/fsspec/asyn.py", line 100, in sync
    raise return_result
  File "/path/to/project/prefect_tutorial/testv/lib/python3.9/site-packages/fsspec/asyn.py", line 55, in _runner
    result[0] = await coro
  File "/path/to/project/prefect_tutorial/testv/lib/python3.9/site-packages/s3fs/core.py", line 1110, in _put_file
    await self._call_s3(
  File "/path/to/project/prefect_tutorial/testv/lib/python3.9/site-packages/s3fs/core.py", line 347, in _call_s3
    return await _error_wrapper(
  File "/path/to/project/prefect_tutorial/testv/lib/python3.9/site-packages/s3fs/core.py", line 139, in _error_wrapper
    raise err
FileNotFoundError: The specified bucket does not exist
An exception occurred.
```

Only thing that changed was the aws/boto packages.

The difference before and after for me looks like:

```
13c13,14
< botocore==1.27.59
---
> boto3==1.26.86
> botocore==1.29.86
51a53,54
> mypy-boto3-s3==1.26.62
> mypy-boto3-secretsmanager==1.26.49
57a61
> prefect-aws==0.2.4
77a82
> s3transfer==0.6.0
```

So botocore upgraded, and some new packages.

My complete working (pre prefect_aws) environment looks like:

```
on 🌱 main [!+?⇡] via 🐍 v3.9.16 (.venv39) ❯ cat pre_prefect_aws.txt 
aiobotocore==2.4.2
aiohttp==3.8.4
aioitertools==0.11.0
aiosignal==1.3.1
aiosqlite==0.18.0
alembic==1.10.1
anyio==3.6.2
apprise==1.3.0
asgi-lifespan==2.0.0
async-timeout==4.0.2
asyncpg==0.27.0
attrs==22.2.0
botocore==1.27.59
cachetools==5.3.0
certifi==2022.12.7
cffi==1.15.1
charset-normalizer==3.1.0
click==8.1.3
cloudpickle==2.2.1
colorama==0.4.6
coolname==2.2.0
croniter==1.3.8
cryptography==39.0.2
dateparser==1.1.7
docker==6.0.1
fastapi==0.93.0
frozenlist==1.3.3
fsspec==2023.3.0
google-auth==2.16.2
greenlet==2.0.2
griffe==0.25.5
h11==0.14.0
h2==4.1.0
hpack==4.0.0
httpcore==0.16.3
httpx==0.23.3
hyperframe==6.0.1
idna==3.4
importlib-metadata==6.0.0
Jinja2==3.1.2
jmespath==1.0.1
jsonpatch==1.32
jsonpointer==2.3
jsonschema==4.17.3
kubernetes==26.1.0
Mako==1.2.4
Markdown==3.4.1
markdown-it-py==2.2.0
MarkupSafe==2.1.2
mdurl==0.1.2
multidict==6.0.4
oauthlib==3.2.2
orjson==3.8.7
packaging==23.0
pathspec==0.11.0
pendulum==2.1.2
prefect==2.8.4
pyasn1==0.4.8
pyasn1-modules==0.2.8
pycparser==2.21
pydantic==1.10.5
Pygments==2.14.0
pyrsistent==0.19.3
python-dateutil==2.8.2
python-slugify==8.0.1
pytz==2022.7.1
pytz-deprecation-shim==0.1.0.post0
pytzdata==2020.1
PyYAML==6.0
readchar==4.0.3
regex==2022.10.31
requests==2.28.2
requests-oauthlib==1.3.1
rfc3986==1.5.0
rich==13.3.2
rsa==4.9
s3fs==2023.3.0
six==1.16.0
sniffio==1.3.0
SQLAlchemy==1.4.46
starlette==0.25.0
text-unidecode==1.3
toml==0.10.2
typer==0.7.0
typing_extensions==4.5.0
tzdata==2022.7
tzlocal==4.2
urllib3==1.26.14
uvicorn==0.20.0
websocket-client==1.5.1
websockets==10.4
wrapt==1.15.0
yarl==1.8.2
zipp==3.15.0
```

# Expectation / Proposal
I didn't expect installing that package would break prefect. I propose we work out what the conflicts are, and either 
specify acceptable versions, or work out why it no longer can find the bucket and fix it.

**Comment by discdiver** [comment]
Closing as this appears to be fixed in the 2.10.8 release from [this PR](https://github.com/PrefectHQ/prefect/issues/8710).
