### ISSUE TITLE
ECSTask fails to cancel paused flows

### ISSUE THREAD

**Issue by EmilRex** [PrefectHQ/prefect-aws#222]
It appears that the agent fails to cancel flow runs that have been paused and rescheduled. Mechanically what happens is:
1. The flow run enters a paused state
2. The ECSTask it's running on exits normally
3. User cancels the flow run
4. Agent attempts to cancel the exited ECSTask and raises an exception

At this point, we should handle the exception, but we don't, so it gets [treated as a generic exception and the agent continues retrying it](https://github.com/PrefectHQ/prefect/blob/e0093a63f7e2bde8da1043a1df15808b7810f4e3/src/prefect/agent.py#L350-L357). It seems like the intention is to [catch it here](https://github.com/PrefectHQ/prefect-aws/blob/ad3c3ede8c7dc9b7dfe6ae8a2f227f84894fcff1/prefect_aws/ecs.py#L690-L694), but perhaps because the original task exited successfully (as opposed to being stopped) a different exception is raised:

```
botocore.errorfactory.InvalidParameterException: An error occurred (InvalidParameterException) when calling the StopTask operation: The referenced task was not found
```

# Expectation / Proposal

The fix is most likely to account for the error:

```py
            if ("not find task" in str(exc)) or ("referenced task was not found" in str(exc)):
                raise InfrastructureNotFound(
                    f"Cannot stop ECS task: the task {task!r} could not be found in "
                    f"cluster {cluster!r}."
                ) from exc
``` 

Assuming this theory is correct, the more complex part is the testing as we're limited by what `moto` offers. The testing comments make it seem like having a `moto` ECSTask complete successfully is difficult.

# Traceback / Example

```
2023-03-20T09:17:14.010-04:00	13:17:14.009 | INFO | prefect.agent - Killing ecs-task prefect-agent-default::arn:aws:ecs:us-east-1:<REDACTED>:task/prefect-agent-default/a79ace98681e4630834050687eb34369 for flow run '84c548c5-4d53-4109-8f48-3a8ac6c7f529'...
2023-03-20T09:17:14.114-04:00	13:17:14.113 | ERROR | prefect.agent - Encountered exception while killing infrastructure for flow run '84c548c5-4d53-4109-8f48-3a8ac6c7f529'. Flow run may not be cancelled.
2023-03-20T09:17:14.114-04:00	Traceback (most recent call last):
2023-03-20T09:17:14.114-04:00	File "/usr/local/lib/python3.10/site-packages/prefect/agent.py", line 344, in cancel_run
2023-03-20T09:17:14.114-04:00	await infrastructure.kill(flow_run.infrastructure_pid)
2023-03-20T09:17:14.114-04:00	File "/usr/local/lib/python3.10/site-packages/prefect_aws/ecs.py", line 668, in kill
2023-03-20T09:17:14.114-04:00	await run_sync_in_worker_thread(self._stop_task, cluster, task)
2023-03-20T09:17:14.114-04:00	File "/usr/local/lib/python3.10/site-packages/prefect/utilities/asyncutils.py", line 91, in run_sync_in_worker_thread
2023-03-20T09:17:14.114-04:00	return await anyio.to_thread.run_sync(
2023-03-20T09:17:14.114-04:00	File "/usr/local/lib/python3.10/site-packages/anyio/to_thread.py", line 31, in run_sync
2023-03-20T09:17:14.114-04:00	return await get_asynclib().run_sync_in_worker_thread(
2023-03-20T09:17:14.114-04:00	File "/usr/local/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 937, in run_sync_in_worker_thread
2023-03-20T09:17:14.114-04:00	return await future
2023-03-20T09:17:14.114-04:00	File "/usr/local/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 867, in run
2023-03-20T09:17:14.114-04:00	result = context.run(func, *args)
2023-03-20T09:17:14.114-04:00	File "/usr/local/lib/python3.10/site-packages/prefect_aws/ecs.py", line 683, in _stop_task
2023-03-20T09:17:14.114-04:00	ecs_client.stop_task(cluster=cluster, task=task)
2023-03-20T09:17:14.114-04:00	File "/usr/local/lib/python3.10/site-packages/botocore/client.py", line 530, in _api_call
2023-03-20T09:17:14.114-04:00	return self._make_api_call(operation_name, kwargs)
2023-03-20T09:17:14.114-04:00	File "/usr/local/lib/python3.10/site-packages/botocore/client.py", line 960, in _make_api_call
2023-03-20T09:17:14.114-04:00	raise error_class(parsed_response, operation_name)
2023-03-20T09:17:14.114-04:00	botocore.errorfactory.InvalidParameterException: An error occurred (InvalidParameterException) when calling the StopTask operation: The referenced task was not found
2023-03-20T09:17:22.494-04:00	13:17:22.494 | INFO | prefect.agent - Found 1 flow runs awa
```

**Comment by madkinsz** [comment]
Is this even an ECS issue or does this happen with any infrastructure?

https://github.com/PrefectHQ/prefect/pull/8414 might be the fix for this

**Comment by madkinsz** [comment]
@EmilRex definitely down for the fix you've proposed as well that sounds correct. We are already patching moto aggressively to make it do what we need it to.

**Comment by jbnitorum** [comment]
@madkinsz It doesn't happen when you run a flow inside an ECS agent task, only when running on ECS as a remote infrastructure block.  [https://github.com/PrefectHQ/prefect/pull/8414](PrefectHQ/prefect/pull/8414) might do the trick.  Ultimately when cancelling a paused (no infra running) flow using the API our plan is to change the flow state directly to 'Cancelled'.  This only really applies for the UI as the cancel button changes state to 'Cancelling' and is then reliant on something else (the agent I guess) to take from Cancelling -> Cancelled.

**Comment by madkinsz** [comment]
@jbnitorum yep that's exactly what we're doing in our pull request!

**Comment by EmilRex** [comment]
This still does not appear to be fixed for @jbnitorum. After upgrading the agent to include https://github.com/PrefectHQ/prefect/pull/8414, the agent was able to transition flow runs from Cancelling to Cancelled, but after running for approximately 6 days, the error started happening again. The agent had not been restarted in this time.

> Something to do with the agent start time/date or duration the agent has been running must be an input for finding flows to move from cancelling to cancelled.

The error is the very same `The referenced task was not found`.

As soon as the agent is restarted, it is able to successfully transition the Cancelling flow runs to Cancelled.

**Comment by madkinsz** [comment]
@EmilRex https://github.com/PrefectHQ/prefect/pull/8414 is a server-side change so upgrading the agent to include it should not change anything.

**Comment by EmilRex** [comment]
Ah, interesting. I didn't realize that. Regardless, the agent appears to be able to transition flow runs from Cancelling to Canceled on startup that it was previously unable to. Any ideas as to why that might be?

**Comment by jbnitorum** [comment]
Actually just to clarify here there is no error message on the agent.  There are no logs in reference to cancelling flows whatsoever, errors or not.  

From what I can tell the agent seems to be able to move flows from 'Cancelling' to 'Cancelled' for ~24 hours after the agent starts.  I haven't tested this precisely, but our agent that started 2 days ago was unable to transition flows to 'Cancelled' this morning.  After that flows that are moved to 'Cancelling' remain in that state indefinitely and nothing is logged to the agent with regards to cancellation, no errors.  Given that it works and then stops working I was guessing that there may be something in the query for cancellable flow runs that references the date/time the agent started running.

Our agent is running as a ECS Fargate Task.

**Comment by madkinsz** [comment]
Probably related to https://github.com/PrefectHQ/prefect/blob/1e10f4183a85ca53876c2a9443f7a96b5ab08ec2/src/prefect/agent.py#L272 — the agent will not attempt to process cancelling runs more than once. If a given agent failed to do so, it will not revisit it. 

Separately, I'll fix this issue in #238 by adding this string to the exception match.

**Comment by jbnitorum** [comment]
Sorry, I think some of the earlier details from this thread are a little misleading.  I'm not entirely clear how the ECSWorker update would effect this.  We are using an ECS Task... in the most literal sense... not a Prefect ECSTask block as our agent.  Our agent was created from the below recipe with some minor changes as our flows are running on ECSTask blocks rather than inside the agent task.  This does install prefect-aws on the agent task, so maybe I'm just confused.

https://github.com/PrefectHQ/prefect-recipes/tree/main/devops/infrastructure-as-code/aws/tf-prefect2-ecs-agent

**Comment by madkinsz** [comment]
@jbnitorum I fixed this in the `ECSTask` implementation before copying over the implementation for the `ECSWorker`

https://github.com/PrefectHQ/prefect-aws/pull/238/commits/4a632ce48d3f79994858468d7d492410690e65d7#diff-31c73194d9fd094cabf83de9a5de6fb5be3f781ad540ed40f1cd4da589c49e4b
