### ISSUE TITLE
Flow deployments with ECSTask infra block have undocumented restrictions on flow name characters

### ISSUE THREAD

**Issue by austinweisgrau** [PrefectHQ/prefect-aws#223]
Prefect flows that are deployed with the ECSTask infrastructure block will raise an error when a prefect agent tries to execute a flow run if there are certain characters in the flow name that are not allowed in ECS task tags.

```botocore.errorfactory.InvalidParameterException: An error occurred (InvalidParameterException) when calling the RunTask operation: Some tags contain invalid characters. Valid characters: UTF-8 letters, spaces, numbers and _ . / = + - : @.```

The error seems to be because the flow name defined with the `name` argument on the `prefect.flow` decorator gets passed to ECS as a tag, and these tags have restricted characters.

# Expectation / Proposal
This restriction should either be clearly documented, or the illegal characters should be escaped or cleaned before attempting to create a tag in ECS.

# Traceback / Example

```
from prefect import flow

@flow(name="Hello World: ' ")
def helloworld():
    pass
```

Deployed with:
```
prefect deployment build helloworld.py:helloworld -q dataflowops -a -n helloworld -ib ecs-task/prod
```

When a deployment run is triggered, the flow run goes directly to a failed state. The state message reported in the UI is `State Message
Submission failed. botocore.errorfactory.InvalidParameterException: An error occurred (InvalidParameterException) when calling the RunTask operation: Some tags contain invalid characters. Valid characters: UTF-8 letters, spaces, numbers and _ . / = + - : @. `

The full traceback from the prefect agent:
```
17:56:02.338 | INFO    | prefect.agent - Submitting flow run 'acaaf129-072e-44de-9769-e6dae28b01fd'
17:56:02.885 | INFO    | prefect.infrastructure.ecs-task - ECSTask 'micro-pig': Retrieving task definition 'arn:aws:ecs:us-east-1:934104411205:task-definition/dataflowops:4'...
17:56:02.990 | INFO    | prefect.infrastructure.ecs-task - ECSTask 'micro-pig': Retrieving task definition 'dataflowops'...
17:56:03.018 | WARNING | prefect.infrastructure.ecs-task - ECSTask 'micro-pig': Settings require changes to the linked task definition. A new task definition will be registered.
17:56:03.430 | INFO    | prefect.infrastructure.ecs-task - ECSTask 'micro-pig': Creating task run...
17:56:03.713 | ERROR   | prefect.agent - Failed to submit flow run 'acaaf129-072e-44de-9769-e6dae28b01fd' to infrastructure.
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/prefect/agent.py", line 476, in _submit_run_and_capture_errors
    result = await infrastructure.run(task_status=task_status)
  File "/usr/local/lib/python3.9/site-packages/prefect_aws/ecs.py", line 610, in run
    ) = await run_sync_in_worker_thread(
  File "/usr/local/lib/python3.9/site-packages/prefect/utilities/asyncutils.py", line 91, in run_sync_in_worker_thread
    return await anyio.to_thread.run_sync(
  File "/usr/local/lib/python3.9/site-packages/anyio/to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/usr/local/lib/python3.9/site-packages/anyio/_backends/_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "/usr/local/lib/python3.9/site-packages/anyio/_backends/_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "/usr/local/lib/python3.9/site-packages/prefect_aws/ecs.py", line 801, in _create_task_and_wait_for_start
    self._report_task_run_creation_failure(task_run, exc)
  File "/usr/local/lib/python3.9/site-packages/prefect_aws/ecs.py", line 797, in _create_task_and_wait_for_start
    task = self._run_task(ecs_client, task_run)
  File "/usr/local/lib/python3.9/site-packages/prefect_aws/ecs.py", line 1458, in _run_task
    return ecs_client.run_task(**task_run)["tasks"][0]
  File "/usr/local/lib/python3.9/site-packages/botocore/client.py", line 508, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/usr/local/lib/python3.9/site-packages/botocore/client.py", line 915, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.errorfactory.InvalidParameterException: An error occurred (InvalidParameterException) when calling the RunTask operation: Some tags contain invalid characters. Valid characters: UTF-8 letters, spaces, numbers and _ . / = + - : @.
17:56:03.716 | INFO    | prefect.agent - Completed submission of flow run 'acaaf129-072e-44de-9769-e6dae28b01fd'
```

- [ ] I would like to [help contribute](https://PrefectHQ.github.io/prefect-aws/#contributing) a pull request to resolve this!

**Comment by madkinsz** [comment]
We should clean these using `slugify` like we do for Kubernetes job annotations. Contributions are welcome here.
