### ISSUE TITLE
AwsSecret block fails to read string secrets

### ISSUE THREAD

**Issue by R1cardoLuiz** [PrefectHQ/prefect-aws#262]
# Expectation / Proposal

The execution of the following code should be successful:

`my_string_secret = AwsSecret.load("my-secret-block-name").read_secret()
`
# Traceback / Example

But got the error below, instead:

```
File ...venv/lib/python3.11/site-packages/prefect_aws/secrets_manager.py", line 409, in read_secret
    secret = response["SecretBinary"]
             ~~~~~~~~^^^^^^^^^^^^^^^^
KeyError: 'SecretBinary'
```

To fix this, the line 409 should be the following:

` secret = response.get("SecretString") or response.get("SecretBinary")`

The error occurs because the secret can be `string ` or `binary`.

- [ ] I would like to [help contribute](https://PrefectHQ.github.io/prefect-aws/#contributing) a pull request to resolve this!

**Comment by mahiki** [comment]
@R1cardoLuiz suggested fix should work. The [method definition for read_secret() task uses that](https://github.com/PrefectHQ/prefect-aws/blob/3a790e0f56d08f9268788dd8d6a95b27eb282db4/prefect_aws/secrets_manager.py#L76)

I ran into this same issue, trying to read secret:

```py
from prefect_aws.secrets_manager import AwsSecret

aws_secret = AwsSecret(
    secret_name=PREFECT_TRINO_SECRETNAME
    , aws_credentials=AwsCredentials.load(PREFECT_AWS_SERVICE_USER)
    )
aws_secret.read_secret()

# My secret is stored as a string json '{"user": "muh_user", ..etc}'
```
stack trace:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/merlinr/Library/Caches/pypoetry/virtualenvs/zhl-wbr-4hu7XBP5-py3.11/lib/python3.11/site-packages/prefect/utilities/asyncutils.py", line 260, in coroutine_wrapper
    return call()
           ^^^^^^
  File "/Users/merlinr/Library/Caches/pypoetry/virtualenvs/zhl-wbr-4hu7XBP5-py3.11/lib/python3.11/site-packages/prefect/_internal/concurrency/calls.py", line 245, in __call__
    return self.result()
           ^^^^^^^^^^^^^
  File "/Users/merlinr/Library/Caches/pypoetry/virtualenvs/zhl-wbr-4hu7XBP5-py3.11/lib/python3.11/site-packages/prefect/_internal/concurrency/calls.py", line 173, in result
    return self.future.result(timeout=timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.2_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/concurrent/futures/_base.py", line 449, in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.2_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/concurrent/futures/_base.py", line 401, in __get_result
    raise self._exception
  File "/Users/merlinr/Library/Caches/pypoetry/virtualenvs/zhl-wbr-4hu7XBP5-py3.11/lib/python3.11/site-packages/prefect/_internal/concurrency/calls.py", line 218, in _run_async
    result = await coro
             ^^^^^^^^^^
  File "/Users/merlinr/Library/Caches/pypoetry/virtualenvs/zhl-wbr-4hu7XBP5-py3.11/lib/python3.11/site-packages/prefect_aws/secrets_manager.py", line 409, in read_secret
    secret = response["SecretBinary"]
             ~~~~~~~~^^^^^^^^^^^^^^^^
KeyError: 'SecretBinary'
```
