### ISSUE TITLE
boto3 import error

### ISSUE THREAD

**Issue by zzstoatzz** [PrefectHQ/prefect-aws#288]
encountering an import error when trying to define an `AwsCredentials` block programmatically:
```
from prefect_aws import AwsCredentials
```

# Expectation / Proposal

# Traceback / Example

```
Traceback (most recent call last):
  File "ecs_block.py", line 8, in <module>
    from prefect_aws import AwsCredentials
  File "/home/a_user/prefect_2_repo/prefect_2_venv/lib/python3.8/site-packages/prefect_aws/__init__.py", line 2, in <module>
    from .credentials import AwsCredentials, MinIOCredentials
  File "/home/a_user/prefect_2_repo/prefect_2_venv/lib/python3.8/site-packages/prefect_aws/credentials.py", line 6, in <module>
    import boto3
  File "/home/a_user/prefect_2_repo/prefect_2_venv/lib/python3.8/site-packages/boto3/__init__.py", line 17, in <module>
    from boto3.session import Session
  File "/home/a_user/prefect_2_repo/prefect_2_venv/lib/python3.8/site-packages/boto3/session.py", line 25, in <module>
    from .resources.factory import ResourceFactory
  File "/home/a_user/prefect_2_repo/prefect_2_venv/lib/python3.8/site-packages/boto3/resources/factory.py", line 17, in <module>
    from ..docs import docstring
  File "/home/a_user/prefect_2_repo/prefect_2_venv/lib/python3.8/site-packages/boto3/docs/__init__.py", line 15, in <module>
    from botocore.docs import DEPRECATED_SERVICE_NAMES
ImportError: cannot import name 'DEPRECATED_SERVICE_NAMES' from 'botocore.docs' (/home/a_user/prefect_2_repo/prefect_2_venv/lib/python3.8/site-packages/botocore/docs/__init__.py)
```

- [x] I would like to [help contribute](https://PrefectHQ.github.io/prefect-aws/#contributing) a pull request to resolve this!

**Comment by desertaxle** [comment]
@zzstoatzz can you share the output of `pip freeze` for the virtual environment where you're getting this error?

**Comment by zzstoatzz** [comment]
I no longer see this error when using `AwsCredentials` - closing issue
